trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    chmod +x ./hyperexecute_linux
    ./hyperexecute_linux --user himanshigupta --key mieWXJBENSSzM4OZ8Lav439gUxq9pYmKKGlf7yxigqpI37CIcN --config yaml/linux/pytest_hyperexecute_autosplit_sample.yaml --env stage --verbose
  displayName: 'run HE test'
