name: hyperexecute_run
on: push
jobs:
  golangci:
    name: hyperexecute grid testing
    runs-on: macos-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
        
      - name: 'provide access to file'
        run: chmod +x ./hyperexecute_mac
        
      - name: run test
        run: ./hyperexecute_mac --user himanshigupta --key mieWXJBENSSzM4OZ8Lav439gUxq9pYmKKGlf7yxigqpI37CIcN --config yaml/mac/pytest_hyperexecute_autosplit_sample.yaml --env stage --verbose
